export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const ADD_STRAINS = 'ADD_STRAINS';
export const STRAINS_LOADING = 'STRAINS_LOADING';
export const STRAINS_FAILED = 'STRAINS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_STRAIN_COMMENT = 'ADD_STRAIN_COMMENT';
export const ADD_STRAIN_COMMENTS = 'ADD_STRAIN_COMMENTS';
export const STRAIN_COMMENTS_FAILED = 'STRAIN_COMMENTS_FAILED';

export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
export const FEEDBACK_FAILED = 'FAILED_FAILED';